githubRepoOwner: wormhole-foundation
githubRepoName: wormhole
githubHost: github.com
requireChecks: true
requireApproval: true
githubRemote: origin
githubBranch: main
              - name: Attest Build Provenance
                uses: actions/attest-build-provenance@v1.4.3
            
